# .github/workflows/deploy.yml
name: Build and Deploy
run-name: Run ${{ github.run_id }} of branch ${{ github.ref_name }}
on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
jobs:
  build-and-check:
    runs-on: self-hosted
    strategy:
      matrix:
        php-version: [ 7.4, 8.1, 8.2 ]
    outputs:
      id: dockerfiles
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and export
        uses: docker/build-push-action@v5
        with:
          file: ${{ matrix.php-version }}/Dockerfile
          context: ${{ matrix.php-version }}
          tags: lancastersolutions/lap:${{ matrix.php-version }}
          outputs: type=docker,dest=/tmp/lap${{ matrix.php-version }}.tar
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: lap${{ matrix.php-version }}
          path: /tmp/lap${{ matrix.php-version }}.tar

  deploy-to-registry:
    needs: build-and-check
    runs-on: self-hosted
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    strategy:
      matrix:
        php-version: [ 7.4, 8.1, 8.2 ]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Download Docker Images Artifact
        uses: actions/download-artifact@v3
        with:
          name: lap${{ matrix.php-version }}
          path: /tmp/lap${{ matrix.php-version }}.tar
      - name: Log into DockerHub Registry
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Load and Push Docker Images
        run: |
          docker load -i /tmp/lap${{ matrix.php-version }}.tar
          docker push lancastersolutions/lap:${{ matrix.php-version }}
